//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stiem_market.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendUsers
    {
        public int ID { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Friend_id { get; set; }
        public Nullable<int> RelationType { get; set; }
        public Nullable<int> Sender_id { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual FriendsRelations FriendsRelations { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
