//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stiem_market.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInCarts
    {
        public int ID { get; set; }
        public Nullable<int> Game_id { get; set; }
        public Nullable<int> Cart_id { get; set; }
        public Nullable<int> PurchasedCost { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Carts Carts { get; set; }
    }
}
