//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stiem_market.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StiemEntities : DbContext
    {
        public StiemEntities()
            : base("name=StiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devs> Devs { get; set; }
        public virtual DbSet<FriendsRelations> FriendsRelations { get; set; }
        public virtual DbSet<GameInCarts> GameInCarts { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<GameTags> GameTags { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserToGameRelation> UserToGameRelation { get; set; }
        public virtual DbSet<FriendUsers> FriendUsers { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<GameShowcase> GameShowcase { get; set; }
    }
}
