//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stiem_market.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGames
    {
        public int ID { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Game_id { get; set; }
        public Nullable<bool> IsWished { get; set; }
        //public Nullable<bool> IsInCart { get; set; }
        public Nullable<bool> IsPurchased { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
